'use strict';
const products=window.BEAN_PRODUCTS,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const upcoming=p=>p.category==='merch'||p.comingSoon===true;
const priceLabel=p=>[p.price==null?'':money(p.price),upcoming(p)&&p.showLaunchBadge!==false?(p.launchLabel??'Coming soon'):''].filter(Boolean).join(' · ')||(!upcoming(p)?'Sold out':'');
const money=v=>v==null?'Price to be confirmed':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const pages={tea:{kicker:'THE BOTANICAL COLLECTION',title:'A slower sip.<br><em>A brighter ritual.</em>',text:'Discover our herbs, flowers, roots, and botanical blends. Explore familiar favorites and find something wonderfully new.',note:'33 herbs & teas<br>from the Bean Bros Whatnot catalog',label:'Herbs, tea & a little curiosity.',description:'Find your flavor. Explore preparation, pairings, and package details.'},merch:{kicker:'WEAR YOUR DAILY RITUAL',title:'Good beans.<br><em>Great company.</em>',text:'A few everyday favorites, made unmistakably Bean Bros. Quiet details, easy colors, and a logo worth taking along.',note:'3 merchandise concepts<br>made to feel like us',label:'A little Bean Bros. Everywhere.',description:'An early look at our apparel and everyday carry collection.'},accessories:{kicker:'THOUGHTFUL TOOLS, BETTER MOMENTS',title:'Make room for<br><em>your ritual.</em>',text:'A beautiful mug. A simple pour. Considered essentials for whatever you’re brewing today.',note:'Shop available accessories<br>See each item for launch status',label:'The finishing touches.',description:'Shop available mugs and explore what is coming next.'}};
let category='tea',filter='All',search='',selected=null,bag=[];
function art(p,mode='card'){
 if(p.productRender)return `<div class="mug-render"><img src="${p.images[0]}" alt="${esc(p.name)}" loading="lazy"></div>`;
 if(p.concept)return `<div class="concept-image crop-${p.col} ${p.category}"><img src="${p.images[0]}" alt="${esc(p.name)} design concept" loading="lazy"></div>`;
 return `<div class="cutout-image ${p.type==='Bundles'?'bundle-image':''}"><img src="assets/herbs/${p.id}-front.png" alt="${esc(p.name)} product on a transparent background" loading="lazy"></div>`;
}
function back(p){
 if(p.backMockup){const labels=p.backLabel?[{src:p.backLabel,name:p.name}]:(p.backLabels||[]);return `<figure class="source-back"><img src="${esc(p.backMockup)}" alt="${esc(p.name)} back packaging mockup"><figcaption>Back package mockup</figcaption></figure>`+labels.map(label=>`<figure class="source-back"><img src="${esc(label.src)}" alt="${esc(label.name)} back sticker"><figcaption>${esc(label.name)} back sticker</figcaption></figure>`).join('');}
 if(p.backLabel)return `<figure class="source-back"><img src="${esc(p.backLabel)}" alt="${esc(p.name)} back sticker"><figcaption>Back sticker</figcaption></figure>`;
 if(p.backKind==='source')return `<figure class="source-back"><img src="${p.images[1]||p.images[0]}" alt="${esc(p.name)} back packaging shown in original listing"><figcaption>Back packaging · Original listing image</figcaption></figure>`;
 const contents=p.subtitle===p.name?p.name:p.subtitle;
 return `<figure class="mock-back"><div class="back-canvas"><img src="assets/back-template.png" alt="Black pouch back packaging mockup"><div class="back-label"><b>BEAN BROS</b><h3>${esc(p.name)}</h3><small>${esc(contents)}</small><hr><strong>${p.type==='Bundles'?'IN THE BUNDLE':'BOTANICAL'}</strong><p>${esc(contents)}</p>${p.prep?`<strong>HOW TO ENJOY</strong><p>${esc(p.prep)}</p>`:''}<b>${esc(p.size)}</b><small class="mock-stamp">BACK PACKAGING MOCKUP</small></div></div><figcaption>Back packaging mockup · Based on listing text</figcaption></figure>`;
}
function renderGrid(){
 let rows=products.filter(p=>p.category===category&&(filter==='All'||p.type===filter)&&(!search||(p.name+' '+p.subtitle+' '+p.description).toLowerCase().includes(search.toLowerCase())));
 $('#products').innerHTML=rows.map(p=>`<article class="product-card"><button class="product-image" data-product="${p.id}" aria-label="View ${esc(p.name)}">${art(p)}<span class="product-badge" ${p.showLaunchBadge===false?'hidden':''}>${upcoming(p)?esc(p.launchLabel??'Coming soon'):p.purchasable?'AVAILABLE NOW':p.concept?'SOLD OUT':p.inactive?'UNAVAILABLE':p.type==='Bundles'?'HERB BUNDLE':p.size}</span><span class="view-product">Explore +</span></button><div class="card-title"><h3><button data-product="${p.id}">${esc(p.name)}</button></h3><span>${esc(priceLabel(p))}</span></div><p>${esc(p.subtitle)}</p>${!p.concept?`<div class="card-meta">${esc(p.flavor||p.caffeine||p.size)}</div>`:''}</article>`).join('')||'<p class="empty">No matching products. Try another herb or clear the search.</p>';
 $('#result-count').textContent=rows.length+' products';
}
function render(){category=Object.hasOwn(pages,location.hash.slice(1))?location.hash.slice(1):category;if(category==='tea'){location.replace('/#tea');return}filter='All';search='';let page=pages[category];
 for(let key of ['kicker','title','text','note'])$('#hero-'+key).innerHTML=page[key];$('#hero-number').textContent=String(products.filter(p=>p.category===category).length).padStart(2,'0');$('#collection-title').textContent=page.label;$('#collection-description').textContent=page.description;
 document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===category);a.setAttribute('aria-current',a.dataset.nav===category?'page':'false')});
 $('#hero-art').innerHTML=category==='tea'?`<div class="herb-hero"><img src="assets/herbs/herb-18-front.png" alt="Lavender Bloom packaging"><span class="hero-art-caption">LAVENDER BLOOM · THE BOTANICAL COLLECTION</span></div>`:`<img class="collection-photo" src="assets/${category}.png" alt="Bean Bros ${category} collection concepts">`;
 let types=['All',...new Set(products.filter(p=>p.category===category).map(p=>p.type))];$('#filters').innerHTML=`<div class="filter-buttons">${types.map(t=>`<button data-filter="${esc(t)}" aria-pressed="${t==='All'}">${esc(t)}</button>`).join('')}</div><label class="search-label"><span class="sr-only">Search products</span><input id="search" type="search" placeholder="Search the collection"></label><span id="result-count" aria-live="polite"></span>`;
 $('#package-art').innerHTML=`<div class="gift-box"><img src="assets/full.png" alt="Bean Bros logo"><span>GOOD BEANS. BETTER DAYS.</span></div><div class="gift-card"><b>Something good<br>is brewing.</b><p>Bean Bros Brewing Co.</p></div>`;
 renderGrid();
}
function showProduct(id){const live=products.find(p=>p.id===id);if(live?.purchasable){location.assign('/?product='+live.productId);return}selected=products.find(p=>p.id===id);if(!selected)return;let p=selected;
 $('#product-name').textContent=p.name;$('#detail-type').textContent=p.type;$('#detail-description').textContent=p.concept?p.description:(p.flavor?`${p.subtitle}. ${p.flavor}`:p.subtitle);$('#detail-price').textContent=priceLabel(p);
 $('#detail-art').innerHTML=p.concept?`${art(p)}<p class="caption">${p.comingSoon?'Coming soon · Product render':'Product and packaging design concept'}</p>`:`<div class="view-buttons"><button data-view="front" aria-pressed="true">Front</button><button data-view="back" aria-pressed="false">Back${p.backKind==='mockup'?' · Mockup':''}</button><button data-view="original" aria-pressed="false">Original image</button></div><div id="package-view">${art(p,'detail')}</div>`;
 $('#variant').innerHTML=p.variants.map(v=>`<option>${esc(v)}</option>`).join('');$('#quantity').value=1; document.querySelector('#product-form button[type=submit]').textContent=upcoming(p)?(p.launchLabel??'Coming soon'):'Sold out'; for(const el of document.querySelectorAll('#product-form label, #variant, #quantity'))el.hidden=!!p.comingSoon;$('#detail-status').textContent=p.concept?'Design concept. Final specifications and pricing are pending.':p.inactive?'Inactive on Whatnot. Shown for catalog planning.':'Whatnot listing captured September 6, 2026. This preview does not reserve stock.';
 document.querySelector('#product-form button[type=submit]').disabled=true;
 $('#product-form .product-information')?.remove();
 if(!p.concept){let info=document.createElement('div');info.className='product-information';info.innerHTML=`${p.caffeine?`<p class="caffeine">${esc(p.caffeine)}</p>`:''}${p.prep?`<h3>How to enjoy</h3><p>${esc(p.prep)}</p>`:''}${p.note?`<p class="source-note">${esc(p.note)}</p>`:''}<details><summary>Full Whatnot description</summary><p class="source-description">${esc(p.description)}</p></details>`;$('#product-form').append(info);}
 $('#product-dialog').showModal();
}
function renderBag(){ $('#count').textContent=bag.reduce((a,p)=>a+p.quantity,0);$('#bag-items').innerHTML=bag.length?bag.map((b,i)=>`<div class="bag-row"><div><b>${esc(b.name)}</b><p>${esc(b.variant)} · Qty ${b.quantity}</p></div><span>${money(b.quantity*b.price)}</span><button data-remove="${i}" aria-label="Remove ${esc(b.name)}">×</button></div>`).join(''):'<p>Your preview bag is empty.</p>';$('#subtotal').textContent=money(bag.reduce((a,p)=>a+p.quantity*p.price,0));}
document.addEventListener('click',e=>{let t=e.target.closest('button');if(!t)return;if(t.dataset.product)showProduct(t.dataset.product);if(t.dataset.filter){filter=t.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',b===t));renderGrid();}if(t.hasAttribute('data-close'))t.closest('dialog').close();if(t.dataset.view&&selected){let v=t.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b===t));$('#package-view').innerHTML=v==='front'?art(selected,'detail'):v==='back'?back(selected):`<img class="original-image" src="${selected.images[0]}" alt="Complete original listing image">`;}if(t.dataset.remove!==undefined){bag.splice(Number(t.dataset.remove),1);renderBag();}});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;renderGrid();}});
$('#product-form').addEventListener('submit',e=>{e.preventDefault();if(!selected||selected.comingSoon||selected.inactive||selected.price==null)return;let quantity=Number($('#quantity').value);if(!Number.isInteger(quantity)||quantity<1||quantity>10)return;bag.push({...selected,variant:$('#variant').value,quantity});renderBag();$('#product-dialog').close();$('#bag-dialog').showModal();});
$('#bag-open').addEventListener('click',()=>{renderBag();$('#bag-dialog').showModal();});
window.addEventListener('hashchange',()=>{if(Object.hasOwn(pages,location.hash.slice(1))){render();window.scrollTo({top:0,behavior:'instant'});}});render();renderBag();
