const {test}=require('node:test'),assert=require('node:assert/strict');
const {loader,event}=require('./helpers.cjs');
const defaults=require('../netlify/functions/lib/accessory-defaults.json');
function setup(authorized=true){const saved=new Map(),rows=[{id:910001,price:25,stock:20,weight:'12 oz',active:true}];const h=loader({'./lib/accessory-products':{ids:{'travel-mug':910001,'speckled-mug':910002},list:async()=>rows,save:async p=>{const i=rows.findIndex(r=>r.id===910001);rows[i]={id:910001,price:p.price,stock:p.stock,weight:p.weight,active:p.active&&!p.comingSoon}}},'./lib/shipping-rates':{netWeightLbs:w=>{if(!/^\d+ oz$/.test(w))throw Error('Weight required');return 1}},'./lib/accessory-defaults.json':defaults,'./lib/banner-defaults.json':require('../netlify/functions/lib/banner-defaults.json'),'./lib/auth':{verifyAdminToken:()=>authorized},'@netlify/blobs':{connectLambda(){},getStore:()=>({get:async id=>saved.get(id)||null,setJSON:async(id,p)=>saved.set(id,p)})}})('netlify/functions/accessories.js').handler;return {h,saved}}
const edit={id:'travel-mug',name:'Updated travel mug',subtitle:'New finish',description:'New description',active:false,price:24.99,imageKey:'product-travel-mug-123.png'};
test('accessory writes require admin authentication',async()=>{const x=setup(false);assert.equal((await x.h(event(edit,{httpMethod:'PUT'}))).statusCode,401);assert.equal(x.saved.size,0)});
test('editing an accessory persists its display fields without changing other previews',async()=>{const x=setup();assert.equal((await x.h(event(edit,{httpMethod:'PUT'}))).statusCode,200);const r=JSON.parse((await x.h(event({}, {httpMethod:'GET'}))).body);const mug=r.items.find(p=>p.id===edit.id);assert.equal(mug.name,edit.name);assert.equal(mug.active,false);assert.equal(mug.price,24.99);assert.equal(mug.images[0],'/.netlify/functions/image?key='+edit.imageKey);assert.equal(r.items.find(p=>p.id==='speckled-mug').name,'Bean Bros Speckled Mug');assert.equal(x.saved.size,1)});
test('invalid IDs, prices and image paths cannot be saved',async()=>{const x=setup();for(const p of [{...edit,id:'unknown'},{...edit,price:-1},{...edit,imageKey:'https://evil.test/x'},{...edit,name:''}])assert.equal((await x.h(event(p,{httpMethod:'PUT'}))).statusCode,400);assert.equal(x.saved.size,0)});

test('banner changes persist independently of accessory prices and descriptions',async()=>{const x=setup();const banner={...require('../netlify/functions/lib/banner-defaults.json'),kind:'banner',title:'New arrivals',visible:false,itemLabel:'Launching soon'};assert.equal((await x.h(event(banner,{httpMethod:'PUT'}))).statusCode,200);const data=JSON.parse((await x.h(event({}, {httpMethod:'GET'}))).body);assert.equal(data.banner.title,'New arrivals');assert.equal(data.banner.visible,false);assert.equal(data.items[0].name,defaults[0].name);assert.equal((await x.h(event({...banner,title:''},{httpMethod:'PUT'}))).statusCode,400)});

test('per-item coming-soon settings persist and live listings expose real checkout IDs',async()=>{const x=setup();let r=JSON.parse((await x.h(event({}, {httpMethod:'GET'}))).body);assert.equal(r.items[0].purchasable,true);assert.equal(r.items[0].productId,910001);assert.equal((await x.h(event({...edit,active:true,comingSoon:true,launchLabel:'Launching in October',showLaunchBadge:false,stock:20,weight:'12 oz'},{httpMethod:'PUT'}))).statusCode,200);r=JSON.parse((await x.h(event({}, {httpMethod:'GET'}))).body);assert.equal(r.items[0].comingSoon,true);assert.equal(r.items[0].showLaunchBadge,false);assert.equal(r.items[0].purchasable,false)});
