const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('assets/storefront.js','utf8');
function harness({cardFails=false,walletFails=false}={}){
 const calls=[],nodes={};const node=id=>nodes[id]||(nodes[id]={disabled:false,open:true,hidden:false,textContent:''});
 const c={$:node,renderBag(){},bag:[{isSubscription:false}],token:()=>'',closeDialog(){},openDialog(){},showManualCheckout(){},checkoutStartRevision:0,checkoutItems:()=>[{name:'Coffee',quantity:1}],syncDeliveryAutocomplete(){},api:async path=>{calls.push(path);return{publishableKey:'pk_test_example',amount:2000}},window:{BeanBrosPayment:{preload:async()=>calls.push('library'),start:async()=>{calls.push('card');if(cardFails)throw Error('Card failed');return true}},BeanBrosExpress:{start:async()=>{calls.push('wallet');if(walletFails)throw Error('Wallet failed')}}},Promise};
 vm.runInNewContext(source.slice(source.indexOf("$('begin-checkout').onclick="),source.indexOf("$('back-to-bag').onclick=")),c);return{calls,nodes,start:()=>node('begin-checkout').onclick()};
}
test('wallet startup uses one setup request and mounts before manual card fields',async()=>{const h=harness();await h.start();assert.deepEqual(h.calls,['create-checkout-session','library','wallet','card']);assert.equal(h.nodes['payment-placeholder'].hidden,true)});
test('a manual card initialization failure does not remove initialized wallets',async()=>{const h=harness({cardFails:true});await h.start();assert.deepEqual(h.calls,['create-checkout-session','library','wallet','card']);assert.equal(h.nodes['wallet-retry'].hidden,true);assert.equal(h.nodes['payment-placeholder'].textContent,'Card failed')});

test('checkout close clears busy state and invalidates pending payment work',()=>{const calls=[];let close;const c={checkoutStartRevision:3,checkoutTimer:1,autoCheckoutKey:'old',checkingOut:true,paymentSubmitting:true,$:()=>({addEventListener:(name,fn)=>{close=fn}}),clearTimeout(){},resetPayment:()=>calls.push('reset'),renderBag:()=>calls.push('render'),window:{BeanBrosExpress:{destroy:()=>calls.push('wallet')},BeanBrosPayment:{destroy:()=>calls.push('card')}}};const start=source.indexOf("$('delivery-dialog').addEventListener('close'");vm.runInNewContext(source.slice(start,source.indexOf("\n",start)),c);close();assert.equal(c.checkingOut,false);assert.equal(c.paymentSubmitting,false);assert.equal(c.checkoutStartRevision,4);assert.equal(c.autoCheckoutKey,'');assert.deepEqual(calls,['wallet','reset','card','render'])});

test('wallet initialization failure still loads the card form and offers retry',async()=>{const h=harness({walletFails:true});await h.start();assert.deepEqual(h.calls,['create-checkout-session','library','wallet','card']);assert.equal(h.nodes['wallet-retry'].hidden,false);assert.equal(h.nodes['payment-placeholder'].hidden,true);assert.match(h.nodes['wallet-note'].textContent,/card details/)});
