const test=require('node:test'),assert=require('node:assert/strict');const {loader}=require('./helpers.cjs');
const env={GOOGLE_ANALYTICS_ID:'G-TEST123',GOOGLE_ANALYTICS_API_SECRET:'test',META_PIXEL_ID:'1234567',META_CONVERSIONS_ACCESS_TOKEN:'test',TIKTOK_PIXEL_ID:'ABCDEFGHIJKLMNOP',TIKTOK_EVENTS_ACCESS_TOKEN:'test'};
const consent={analytics:true,marketing:true,clientId:'123.456',sessionId:'123',fbp:'fb.1.1234567890123.abc',ttp:'abc'};
const session={id:'cs_test123',livemode:true,status:'complete',payment_status:'paid',currency:'usd',metadata:{measurement:JSON.stringify(consent)},total_details:{amount_tax:200},shipping_cost:{amount_total:500}};
const lines=[{quantity:3,amount_subtotal:3000,amount_discount:100,price:{product:{name:'Coffee',metadata:{product_id:'7'}}}}];
test('paid Stripe values create deduplicated platform events without customer details',()=>{const c=loader({},env)('netlify/functions/lib/conversions.js');const events=c.payloads({...session,customer_email:'private@example.test'},lines,{created:1700000000});assert.equal(events.length,3);assert.equal(events[0].payload.events[0].params.value,29);assert.equal(events[0].payload.events[0].params.shipping,5);assert.ok(!JSON.stringify(events).includes('private@'));assert.equal(events[0].id,c.payloads(session,lines,{created:1700000001})[0].id)});
test('unpaid, test-mode and unconsented sessions cannot emit purchase events',()=>{const c=loader({},env)('netlify/functions/lib/conversions.js');for(const patch of [{livemode:false},{payment_status:'unpaid'},{status:'open'},{metadata:{}},{metadata:{measurement:'invalid'}}])assert.equal(c.payloads({...session,...patch},lines,{}).length,0)});
test('identifiers are validated, consent-separated and fit Stripe metadata limits',()=>{const c=loader({},env)('netlify/functions/lib/conversions.js');const filtered=c.context({...consent,marketing:false,email:'private@example.test'});assert.equal(filtered.fbp,undefined);assert.equal(filtered.email,undefined);assert.equal(c.context({...consent,clientId:'bad\nvalue'}).clientId,undefined);assert.ok(JSON.stringify(c.context({...consent,fbc:'fb.1.1234567890123.'+'x'.repeat(300),ttp:'x'.repeat(200)})).length<=500)});
test('enqueue uses a unique key and SQL parameters for webhook replay safety',async()=>{let calls=[];const c=loader({'./db':{query:async(...args)=>calls.push(args)}},env)('netlify/functions/lib/conversions.js');await c.enqueue(session,lines,{created:1700000000});assert.equal(calls.length,4);for(const [sql,args]of calls.slice(1)){assert.match(sql,/ON CONFLICT DO NOTHING/);assert.equal(args.length,3)}});
