const {test}=require('node:test'),assert=require('node:assert/strict'),{loader,event}=require('./helpers.cjs');
test('unconfigured email dispatch never opens the database',async()=>{
 const h=loader({'./email':{isConfigured:()=>false}})('netlify/functions/customer-email-dispatch.js').handler;
 const result=await h();
 assert.equal(result.statusCode,200);
 assert.equal(JSON.parse(result.body).error,'Email provider is not configured');
});
test('messages queued while email is unconfigured remain deliverable after configuration',async()=>{
 const {PGlite}=require('@electric-sql/pglite'),pg=new PGlite();
 try{
  let configured=false,sent=0;
  const db={query:async(s,a)=>a?(await pg.query(s,a)).rows:(await pg.exec(s)).at(-1).rows,one:async(s,a)=>(await pg.query(s,a)).rows[0]};
  const care=loader({'./db':db,'./email':{isConfigured:()=>configured,send:async()=>{sent++;return {ok:true}}}})('netlify/functions/lib/customer-care.js');
  await care.queue('deferred','buyer@example.test',{subject:'Order confirmed'});
  await care.sendQueued('deferred');
  assert.equal(sent,0);
  assert.equal((await db.one("SELECT status FROM customer_messages WHERE id='deferred'",[])).status,'pending');
  configured=true;
  await care.flush(3);
  await care.flush(3);
  assert.equal(sent,1);
 }finally{await pg.close()}
});
test('public reviews select only approved text without private survey or email',async()=>{let sql;const h=loader({'./lib/customer-care':{schema:async()=>{}},'./lib/db':{query:async s=>{sql=s;return[]}}})('netlify/functions/reviews.js').handler;const r=await h(event({}, {httpMethod:'GET',queryStringParameters:{productId:'1'}}));assert.equal(r.statusCode,200);assert.match(sql,/status='approved'/);assert.doesNotMatch(sql.split('FROM')[0],/email|survey|order_id/)});
test('review moderation is protected before any database access',async()=>{const h=loader({'./lib/auth':{verifyAdminToken:()=>false}})('netlify/functions/admin-customer-care.js').handler;assert.equal((await h(event({action:'moderate',status:'approved'}))).statusCode,401)});
test('reviews reject another customer, unreceived products and test orders',async()=>{for(const which of ['other','unreceived','test']){const care=loader()('netlify/functions/lib/customer-care.js');const h=loader({'./lib/accounts':{requireSession:async()=>({email:'buyer@example.test',user:{name:'Buyer'}})},'./lib/rate-limit':{consumeLimit:async()=>true,clientIp:()=>''},'./lib/customer-care':{...care,schema:async()=>{}},'./lib/orders':{getOrderById:async()=>({id:'o',customerEmail:which==='other'?'other@example.test':'buyer@example.test',accounting:{livemode:which!=='test'},status:which==='unreceived'?'Shipped':'Delivered',items:[{productId:1}]})}})('netlify/functions/reviews.js').handler;assert.ok([403,404].includes((await h(event({orderId:'o',productId:1,rating:5,experience:5,body:'Good tea'}))).statusCode))}});
test('review inserts are pending, duplicate-safe and SQL parameterized',async()=>{let sql,args;const care=loader()('netlify/functions/lib/customer-care.js');const h=loader({'./lib/accounts':{requireSession:async()=>({email:'buyer@example.test',user:{name:'Buyer Person'}})},'./lib/rate-limit':{consumeLimit:async()=>true,clientIp:()=>''},'./lib/customer-care':{...care,schema:async()=>{}},'./lib/orders':{getOrderById:async()=>({id:'o',customerEmail:'buyer@example.test',accounting:{livemode:true},status:'Delivered',items:[{productId:1}]})},'./lib/db':{one:async(s,a)=>{sql=s;args=a;return{id:'r'}}}})('netlify/functions/reviews.js').handler;const r=await h(event({orderId:'o',productId:1,rating:1,experience:2,body:"Not for me <script>bad</script>",packaging:'Private'}));assert.equal(r.statusCode,200);assert.match(sql,/ON CONFLICT.*DO NOTHING/);assert.doesNotMatch(sql,/approved|<script>/);assert.equal(args[6],"Not for me <script>bad</script>");assert.equal(JSON.parse(args[7]).packaging,'Private')});
test('outbox SQL prevents duplicate events and preserves uncertain delivery outcomes',async()=>{const {PGlite}=require('@electric-sql/pglite'),pg=new PGlite();try{const db={query:async(s,a)=>a?(await pg.query(s,a)).rows:(await pg.exec(s)).at(-1).rows,one:async(s,a)=>(await pg.query(s,a)).rows[0]};let sent=0;const care=loader({'./db':db,'./email':{isConfigured:()=>true,send:async()=>{sent++;return {ok:true}}}})('netlify/functions/lib/customer-care.js');await care.queue('event','buyer@example.test',{subject:'Hello'});await care.queue('event','buyer@example.test',{subject:'Hello'});await care.flush();await care.flush();assert.equal(sent,1);await db.query("INSERT INTO customer_messages(id,recipient,payload,status,sent_at) VALUES('stale','buyer@example.test','{}','sending',now()-interval '11 minutes')",[]);await care.flush();assert.equal((await db.one("SELECT status FROM customer_messages WHERE id='stale'",[])).status,'review');assert.equal(sent,1)}finally{await pg.close()}});
test('immediate service email sends only its own message and tracking is duplicate-safe',async()=>{const {PGlite}=require('@electric-sql/pglite'),pg=new PGlite();try{const db={query:async(s,a)=>a?(await pg.query(s,a)).rows:(await pg.exec(s)).at(-1).rows,one:async(s,a)=>(await pg.query(s,a)).rows[0]};const sent=[];const care=loader({'./db':db,'./email':{isConfigured:()=>true,shell:s=>s,esc:s=>String(s),send:async m=>{sent.push(m);return{ok:true}}}})('netlify/functions/lib/customer-care.js');await care.queue('unrelated','other@example.test',{subject:'Other'});const order={id:'BB-TEST',accounting:{livemode:true},customerEmail:'buyer@example.test',trackingNumber:'1ZTEST'};await care.trackingReady(order);await care.trackingReady(order);assert.equal(sent.length,1);assert.equal(sent[0].to,order.customerEmail);assert.match(sent[0].text,/1ZTEST/);assert.match(sent[0].text,/label has been created/);assert.equal((await db.one("SELECT status FROM customer_messages WHERE id='unrelated'",[])).status,'pending');await care.trackingReady({...order,id:'TEST',accounting:{livemode:false}});assert.equal(sent.length,1)}finally{await pg.close()}});
