const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm');
function harness({walletFailure=false,taxReady=true}={}){const calls=[],nodes={};const node=id=>nodes[id]||(nodes[id]={checked:true,value:'buyer@example.test',hidden:false,textContent:'',replaceChildren(){},append(){}});const card={mount:id=>calls.push(['card',id]),on(){},destroy:()=>calls.push(['destroy'])},billing={mount(){},destroy(){}};
 const total={minorUnitsAmount:2877};const actions={updateEmail:async()=>({type:'success'}),updateBillingAddress:async()=>({type:'success'}),getSession:()=>({currency:'usd',minorUnitsAmountDivisor:100,tax:{status:taxReady?'ready':'requires_shipping_address'},total:{subtotal:{minorUnitsAmount:2000},shippingRate:{minorUnitsAmount:777},taxExclusive:{minorUnitsAmount:100},total}}),confirm:async args=>{calls.push(['confirm',args]);return{type:'success'}}};const wallet={on:(name,fn)=>{wallet[name]=fn},mount:id=>calls.push(['wallet',id]),destroy(){}};const stripe={elements:()=>({create:type=>type==='card'?card:billing}),initCheckoutElementsSdk:async()=>({loadActions:async()=>({type:'success',actions}),createExpressCheckoutElement:()=>{if(walletFailure)throw Error('Wallet unavailable');return wallet}}),createPaymentMethod:async()=>({paymentMethod:{id:'pm_test'}})};
 const context={window:{Stripe:()=>stripe},document:{getElementById:node,createElement:()=>({textContent:'',append(){}})},setTimeout,clearTimeout,Promise,Error,Intl,Number};vm.runInNewContext(fs.readFileSync('assets/embedded-payment.js','utf8'),context);return{payment:context.window.BeanBrosPayment,calls,node,wallet}}
const address={name:'Buyer',address:'123 Main',city:'Paramus',state:'NJ',zip:'07652'};
test('card inputs mount before any address or checkout session is supplied',async()=>{const h=harness();assert.equal(await h.payment.start('pk_test_example'),true);assert.equal(h.calls[0][0],'card');assert.equal(h.calls.some(c=>c[0]==='confirm'),false)});
test('preparing the final total never charges; explicit Pay confirms the Stripe payment method',async()=>{const h=harness();await h.payment.start('pk_test_example');assert.equal(await h.payment.prepare({clientSecret:'secret'},address,()=>{}),true);assert.equal(h.node('pay-order').textContent,'Pay $28.77');assert.equal(h.calls.some(c=>c[0]==='confirm'),false);await h.node('pay-order').onclick();assert.equal(h.calls.find(c=>c[0]==='confirm')[1].paymentMethod,'pm_test')});
test('editing shipping invalidates the reviewed payment while retaining entered card details',async()=>{const h=harness();await h.payment.start('pk_test_example');await h.payment.prepare({clientSecret:'secret'},address,()=>{});h.payment.reset();await h.node('pay-order').onclick();assert.equal(h.calls.some(c=>c[0]==='confirm'),false);assert.equal(h.calls.some(c=>c[0]==='destroy'),false);h.payment.destroy();assert.equal(h.calls.some(c=>c[0]==='destroy'),true)});
test('wallet confirmation uses the same reviewed checkout session',async()=>{const h=harness();await h.payment.start('pk_test_example');await h.payment.prepare({clientSecret:'secret'},address,()=>{});const e={paymentFailed(){}};await h.wallet.confirm(e);assert.equal(h.calls.find(c=>c[0]==='confirm')[1].expressCheckoutConfirmEvent,e)});

test('failed wallet initialization clears review and prevents payment confirmation',async()=>{const h=harness({walletFailure:true});await h.payment.start('pk_test_example');await assert.rejects(h.payment.prepare({clientSecret:'secret'},address,()=>{}),/Wallet unavailable/);assert.equal(h.node('pay-order').hidden,true);await h.node('pay-order').onclick();assert.equal(h.calls.some(c=>c[0]==='confirm'),false)});
test('incomplete tax prevents review and confirmation',async()=>{const h=harness({taxReady:false});await h.payment.start('pk_test_example');await assert.rejects(h.payment.prepare({clientSecret:'secret'},address,()=>{}),/Tax could not/);assert.equal(h.node('payment-review').hidden,true);assert.equal(h.calls.some(c=>c[0]==='confirm'),false)});
