const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness({total=2776}={}){
 const events={},calls=[],nodes={};const node=id=>nodes[id]||(nodes[id]={textContent:'',replaceChildren(){}});
 const quote={total:2776,selectedService:'03',options:[{serviceCode:'03',displayName:'UPS Ground',amountCents:777}],lineItems:[{name:'Items',amount:1999},{name:'Shipping',amount:777}]};
 const wallet={on:(n,f)=>events[n]=f,mount:id=>calls.push(['mount',id]),destroy(){}};
 const elements={create:(type,options)=>{calls.push(['element',type,options]);return wallet},update:o=>calls.push(['amount',o]),submit:async()=>({})};
 const actions={updateEmail:async()=>({type:'success'}),updateBillingAddress:async()=>({type:'success'}),getSession:()=>({currency:'usd',tax:{status:'ready'},total:{total:{minorUnitsAmount:total}}}),confirm:async p=>{calls.push(['confirm',p]);return {type:'success'}}};
 const stripe={elements:options=>{calls.push(['elements',options]);return elements},createPaymentMethod:async()=>({paymentMethod:{id:'pm_wallet'}}),initCheckout:()=>({loadActions:async()=>({type:'success',actions})})};
 const c={setTimeout:()=>0,clearTimeout:()=>{},window:{Stripe:()=>stripe},document:{getElementById:node},location:{origin:'https://beanbrosbrewingco.com'},Error};vm.runInNewContext(fs.readFileSync('assets/express-payment.js','utf8'),c);
 const callbacks={request:async body=>{calls.push(['request',body]);return body.action==='wallet-start'?{amount:1999,items:[{name:'Coffee',amount:1999}]}:body.action==='wallet-quote'?quote:{clientSecret:'cs_secret'}},promo:()=>'',busy(){},unavailable(){},remember:()=>calls.push(['remember'])};
 return {api:c.window.BeanBrosExpress,callbacks,events,calls,node};
}
const partial={city:'New York',state:'NY',postal_code:'10118',country:'US'};
function confirmEvent(failed){return {shippingAddress:{name:'Buyer',address:{...partial,line1:'350 Fifth Avenue'}},billingDetails:{email:'buyer@example.test',name:'Buyer',address:{...partial,line1:'350 Fifth Avenue'}},paymentFailed:failed}}
test('express buttons mount before any delivery entry, without creating or confirming a checkout session',async()=>{const h=harness();await h.api.start('pk_test',h.callbacks);assert.equal(h.calls.find(c=>c[0]==='request')[1].action,'wallet-start');assert.ok(h.calls.some(c=>c[0]==='mount'));assert.equal(h.calls.filter(c=>c[0]==='request').length,1);assert.equal(h.calls.find(c=>c[0]==='element')[2].shippingAddressRequired,true)});
test('wallet address selects server quoted shipping and total, then confirms only after wallet approval',async()=>{const h=harness();await h.api.start('pk_test',h.callbacks);await h.events.shippingaddresschange({address:partial,resolve(){},reject(){assert.fail('quote rejected')}});assert.equal(h.calls.some(c=>c[0]==='confirm'),false);await h.events.confirm(confirmEvent(()=>assert.fail('payment failed')));const request=h.calls.find(c=>c[0]==='request'&&c[1].paymentFirst)[1];assert.equal(request.shipTo.address,'350 Fifth Avenue');assert.equal(request.shippingAmount,777);assert.equal(h.calls.find(c=>c[0]==='confirm')[1].paymentMethod,'pm_wallet')});
test('a tax or shipping total change cannot be charged without renewed wallet approval',async()=>{const h=harness({total:3000});await h.api.start('pk_test',h.callbacks);await h.events.shippingaddresschange({address:partial,resolve(){},reject(){}});let failed=false;await h.events.confirm(confirmEvent(()=>failed=true));assert.equal(failed,true);assert.equal(h.calls.some(c=>c[0]==='confirm'),false)});
test('a wallet cannot confirm until a real shipping quote has returned',async()=>{const h=harness();await h.api.start('pk_test',h.callbacks);let failed=false;await h.events.confirm(confirmEvent(()=>failed=true));assert.equal(failed,true);assert.equal(h.calls.some(c=>c[0]==='confirm'),false)});
