const {test}=require('node:test');
const assert=require('node:assert/strict');
const {loader,event}=require('./helpers.cjs');
function admin(authorized=true){const calls=[];const stripe={coupons:{create:async(p,o)=>{calls.push(['coupon',p,o]);return{id:'coupon_test'}}},promotionCodes:{create:async(p,o)=>{calls.push(['promo',p,o]);return{id:'promo_test',code:p.code}},update:async(...a)=>calls.push(['update',...a]),list:async()=>({data:[],has_more:false})}};return {calls,handler:loader({stripe:()=>stripe,'./lib/auth':{verifyAdminToken:()=>authorized}})('netlify/functions/admin-promos.js').handler}}
const valid={code:'welcome10',type:'percent',value:10,limit:5,requestId:'12345678-1234-1234-1234-123456789abc'};
test('promo management requires admin authentication',async()=>{const h=admin(false);assert.equal((await h.handler(event(valid))).statusCode,401);assert.equal(h.calls.length,0)});
test('creates a bounded promotion with idempotent Stripe writes',async()=>{const h=admin();assert.equal((await h.handler(event(valid))).statusCode,200);assert.equal(h.calls[0][1].percent_off,10);assert.equal(h.calls[0][1].duration,'once');assert.equal(h.calls[1][1].code,'WELCOME10');assert.equal(h.calls[1][1].max_redemptions,5);assert.ok(h.calls[0][2].idempotencyKey);assert.ok(h.calls[1][2].idempotencyKey)});
test('fixed discounts use integer USD cents',async()=>{const h=admin();assert.equal((await h.handler(event({...valid,type:'amount',value:5.25}))).statusCode,200);assert.equal(h.calls[0][1].amount_off,525);assert.equal(h.calls[0][1].currency,'usd')});
test('invalid promo inputs never create coupons',async()=>{for(const patch of [{value:101},{value:0},{value:1.001},{limit:-1},{expires:'2020-01-01'},{code:'<script>'},{type:'bogus'},{requestId:''}]){const h=admin();assert.equal((await h.handler(event({...valid,...patch}))).statusCode,400);assert.equal(h.calls.length,0)}});
test('admin can deactivate a promotion',async()=>{const h=admin();assert.equal((await h.handler(event({id:'promo_test'},{httpMethod:'PATCH'}))).statusCode,200);assert.equal(h.calls[0][2].active,false)});
function checkout(promo){let config;const stripe={promotionCodes:{list:async()=>({data:promo?[promo]:[]})},customers:{create:async()=>({id:'cus_test'})},checkout:{sessions:{create:async c=>{config=c;return{id:'cs_test',url:'https://checkout.stripe.com/test'}}}}};const handler=loader({stripe:()=>stripe,'./lib/products':{getProductByName:async()=>({id:1,name:'Coffee',price:20,stock:3,active:true})},'./lib/shipping-config':{getShippingConfig:async()=>({freeShipThreshold:50})},'./lib/ups':{validateAddress:async()=>({verified:true})},'./lib/shipping-rates':{getPackageDetails:()=>({}),getShippingOptions:async()=>[{serviceCode:'03',amountCents:777,minDays:2,maxDays:5}]}})('netlify/functions/create-checkout-session.js').handler;return{handler,config:()=>config}}
const cart={promoCode:'WELCOME10',shipTo:{name:'Customer',address:'123 Main St',city:'Paramus',state:'NJ',zip:'07652',country:'US'},shippingService:'03',shippingAmount:777,items:[{name:'Coffee',quantity:1,grindLabel:'Whole Bean'}],successUrl:'https://beanbrosbrewingco.com/#/checkout-success',cancelUrl:'https://beanbrosbrewingco.com/#/cart'};
test('checkout delegates discount and redemption enforcement to Stripe without changing prices or shipping',async()=>{const h=checkout({id:'promo_test',coupon:{valid:true}});assert.equal((await h.handler(event(cart))).statusCode,200);assert.equal(h.config().discounts[0].promotion_code,'promo_test');assert.equal(h.config().line_items[0].price_data.unit_amount,2000);assert.equal(h.config().shipping_options[0].shipping_rate_data.fixed_amount.amount,777)});
test('invalid expired and exhausted codes never create checkout sessions',async()=>{for(const p of [null,{coupon:{valid:false}},{coupon:{valid:true},expires_at:1},{coupon:{valid:true},max_redemptions:2,times_redeemed:2}]){const h=checkout(p);assert.equal((await h.handler(event(cart))).statusCode,400);assert.equal(h.config(),undefined)}});
