const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness(saved,gpc=false){
 const elements={},buttons=['reject','save','all'].map(choice=>({dataset:{choice}})),scripts=[],store=new Map(saved?[['bb_cookie_consent_v1',JSON.stringify({...saved,at:Date.now()})]]:[]);
 const dialog={setAttribute(){},querySelector:s=>elements[s]??=( {} ),querySelectorAll:()=>buttons,showModal(){this.open=true},close(){this.open=false}};
 const c={Date,URL,navigator:{globalPrivacyControl:gpc},location:{origin:'https://example.test',pathname:'/',hostname:'example.test',reload(){}},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},document:{title:'Shop',referrer:'',cookie:'',head:{append:s=>scripts.push(s.src)},body:{append(){}},querySelector:()=>null,createElement:tag=>tag==='dialog'?dialog:{}},BeanBrosTrackingConfig:{google:'G-TEST123',meta:'123456789',tiktok:'ABCDEFGHIJKLMNOPQRST'}};c.window=c;vm.runInNewContext(fs.readFileSync('assets/tracking.js','utf8'),c);return{c,scripts,dialog,buttons,elements};
}
test('no optional scripts or ecommerce events before consent',()=>{const h=harness();assert.equal(h.scripts.length,0);assert.equal(h.dialog.open,true);h.c.BeanBrosAnalytics.track('add_to_cart',[{product:{id:1,name:'Coffee',price:20},quantity:1}]);assert.equal(h.scripts.length,0);h.buttons[0].onclick();assert.equal(h.scripts.length,0)});
test('analytics-only choice does not load advertising platforms',()=>{const h=harness({analytics:true,marketing:false});assert.equal(h.scripts.length,1);assert.match(h.scripts[0],/googletagmanager/);assert.equal(h.c.fbq,undefined)});
test('all consent enables platforms, sends discounted totals and excludes customer fields',()=>{const h=harness();h.buttons[2].onclick();assert.equal(h.scripts.length,3);h.c.BeanBrosAnalytics.track('add_to_cart',[{product:{id:1,name:'Coffee',price:20},quantity:2,isSubscription:true,email:'private@example.test'}]);const event=h.c.dataLayer.at(-1);assert.equal(event[1],'add_to_cart');assert.equal(event[2].value,36);assert.ok(!JSON.stringify(event).includes('private@'));assert.equal(h.c.fbq.queue.at(-1)[1],'AddToCart');assert.equal(h.c.ttq.at(-1)[1],'AddToCart')});
test('Global Privacy Control suppresses marketing even with saved consent',()=>{const h=harness({analytics:true,marketing:true},true);assert.equal(h.scripts.length,1);assert.equal(h.elements['#cookie-marketing'].disabled,true)});
test('withdrawal revokes consent and stops subsequent custom events',()=>{const h=harness({analytics:true,marketing:true});h.buttons[0].onclick();const before=[h.c.dataLayer.length,h.c.fbq.queue.length,h.c.ttq.length];h.c.BeanBrosAnalytics.track('add_to_cart',[{product:{id:1,name:'Coffee',price:20},quantity:1}]);assert.deepEqual([h.c.dataLayer.length,h.c.fbq.queue.length,h.c.ttq.length],before)});
test('public tracking configuration rejects injection and excludes secrets',()=>{const {fromEnv}=require('../scripts/tracking-config.cjs');assert.throws(()=>fromEnv({GOOGLE_ANALYTICS_ID:'G-<script>'}));assert.deepEqual(fromEnv({ADMIN_TOKEN_SECRET:'secret'}),{google:'',meta:'',tiktok:''})});
test('indexable pages contain canonical and social metadata; private pages remain noindex',()=>{for(const f of ['index.html','privacy.html','terms.html','shipping-returns.html','accessibility.html']){const s=fs.readFileSync(f,'utf8');assert.equal((s.match(/rel="canonical"/g)||[]).length,1);assert.match(s,/property="og:image"/);assert.match(s,/name="twitter:card"/)}for(const f of ['admin.html','account.html','collections/index.html'])assert.match(fs.readFileSync(f,'utf8'),/content="noindex/);assert.match(fs.readFileSync('_redirects','utf8'),/\/\*\s+\/404.html\s+404/)});
