'use strict';
const crypto=require('crypto'),db=require('./db');
function context(input){const x=input&&typeof input==='object'?input:{},out={analytics:x.analytics===true,marketing:x.marketing===true};const fields={clientId:/^\d{1,20}\.\d{1,20}$/,sessionId:/^\d{1,20}$/,fbp:/^fb\.\d\.\d{10,16}\.[A-Za-z0-9_-]{1,200}$/,fbc:/^fb\.\d\.\d{10,16}\.[A-Za-z0-9_-]{1,300}$/,ttp:/^[A-Za-z0-9_-]{1,200}$/};for(const [k,re]of Object.entries(fields)){if(typeof x[k]==='string'&&re.test(x[k])&&(['clientId','sessionId'].includes(k)?out.analytics:out.marketing))out[k]=x[k]}for(const k of ["fbc","fbp","ttp"]){if(JSON.stringify(out).length>480)delete out[k]}return out}
async function schema(){await db.query(`CREATE TABLE IF NOT EXISTS measurement_outbox (id text PRIMARY KEY, platform text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'pending', attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), sent_at timestamptz)`)}
function payloads(session,lines,event){
 if(session.livemode!==true||session.status!=='complete'||session.payment_status!=='paid')return [];
 let c;try{c=context(JSON.parse(session.metadata?.measurement||'{}'))}catch{return []}
 const id='bb_'+crypto.createHash('sha256').update(session.id).digest('hex').slice(0,32),currency=(session.currency||'usd').toUpperCase();
 const items=lines.filter(l=>l.price?.product?.metadata?.kind!=='shipping').map(l=>({item_id:String(l.price?.product?.metadata?.product_id||l.price?.product?.id||''),item_name:l.price?.product?.name||l.description||'Product',quantity:l.quantity,price:((l.amount_subtotal||0)-(l.amount_discount||0))/l.quantity/100}));
 const value=Math.round(items.reduce((n,i)=>n+i.price*i.quantity,0)*100)/100,timestamp=event.created||Math.floor(Date.now()/1000),result=[];
 const contents=items.map(i=>({id:i.item_id,quantity:i.quantity,item_price:i.price}));
 if(c.analytics&&c.clientId&&process.env.GOOGLE_ANALYTICS_ID&&process.env.GOOGLE_ANALYTICS_API_SECRET)result.push({id:id+':google',platform:'google',payload:{client_id:c.clientId,timestamp_micros:timestamp*1000000,consent:{ad_user_data:'DENIED',ad_personalization:'DENIED'},events:[{name:'purchase',params:{transaction_id:id,currency,value,tax:(session.total_details?.amount_tax||0)/100,shipping:((session.shipping_cost?.amount_total||0)+lines.filter(l=>l.price?.product?.metadata?.kind==='shipping').reduce((n,l)=>n+(l.amount_total||0),0))/100,items,...(c.sessionId?{session_id:Number(c.sessionId)}:{}),engagement_time_msec:1}}]}});
 if(c.marketing&&(c.fbp||c.fbc)&&process.env.META_PIXEL_ID&&process.env.META_CONVERSIONS_ACCESS_TOKEN)result.push({id:id+':meta',platform:'meta',payload:{data:[{event_name:'Purchase',event_time:timestamp,event_id:id,action_source:'website',event_source_url:'https://beanbrosbrewingco.com/',user_data:{...(c.fbp?{fbp:c.fbp}:{}),...(c.fbc?{fbc:c.fbc}:{})},custom_data:{currency,value,content_type:'product',contents,order_id:id}}]}});
 if(c.marketing&&c.ttp&&process.env.TIKTOK_PIXEL_ID&&process.env.TIKTOK_EVENTS_ACCESS_TOKEN)result.push({id:id+':tiktok',platform:'tiktok',payload:{event_source:'web',event_source_id:process.env.TIKTOK_PIXEL_ID,data:[{event:'Purchase',event_time:timestamp,event_id:id,user:{ttp:c.ttp},page:{url:'https://beanbrosbrewingco.com/'},properties:{currency,value,order_id:id,contents:items.map(i=>({content_id:i.item_id,content_type:'product',content_name:i.item_name,quantity:i.quantity,price:i.price}))}}]}});
 return result;
}
async function enqueue(session,lines,event){const rows=payloads(session,lines,event);if(!rows.length)return;await schema();for(const r of rows)await db.query(`INSERT INTO measurement_outbox (id,platform,payload) VALUES ($1,$2,$3::jsonb) ON CONFLICT DO NOTHING`,[r.id,r.platform,JSON.stringify(r.payload)])}
async function send(row){let url,headers={'Content-Type':'application/json'};
 if(row.platform==='google'){if(!process.env.GOOGLE_ANALYTICS_API_SECRET||!process.env.GOOGLE_ANALYTICS_ID)throw Error('Unconfigured');url='https://www.google-analytics.com/mp/collect?measurement_id='+encodeURIComponent(process.env.GOOGLE_ANALYTICS_ID)+'&api_secret='+encodeURIComponent(process.env.GOOGLE_ANALYTICS_API_SECRET)}
 else if(row.platform==='meta'){if(!process.env.META_CONVERSIONS_ACCESS_TOKEN||!process.env.META_PIXEL_ID)throw Error('Unconfigured');url='https://graph.facebook.com/v25.0/'+process.env.META_PIXEL_ID+'/events';headers.Authorization='Bearer '+process.env.META_CONVERSIONS_ACCESS_TOKEN}
 else if(row.platform==='tiktok'){if(!process.env.TIKTOK_EVENTS_ACCESS_TOKEN)throw Error('Unconfigured');url='https://business-api.tiktok.com/open_api/v1.3/event/track/';headers['Access-Token']=process.env.TIKTOK_EVENTS_ACCESS_TOKEN}else throw Error('Unknown platform');
 const response=await fetch(url,{method:'POST',headers,body:JSON.stringify(row.payload),signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('Delivery failed');if(row.platform==='tiktok'&&(await response.json()).code!==0)throw Error('Delivery rejected');
}
async function flush(){await schema();const rows=await db.query(`UPDATE measurement_outbox SET status='sending',attempts=attempts+1,available_at=now()+interval '5 minutes' WHERE id IN (SELECT id FROM measurement_outbox WHERE status IN ('pending','sending') AND available_at<=now() AND attempts<8 AND created_at>now()-interval '48 hours' ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 2) RETURNING *`);let sent=0;for(const row of rows){try{await send(row);await db.query("UPDATE measurement_outbox SET status='sent',sent_at=now(),payload='{}'::jsonb WHERE id=$1",[row.id]);sent++}catch{await db.query("UPDATE measurement_outbox SET status='pending',available_at=now()+interval '15 minutes' WHERE id=$1",[row.id])}}
 await db.query("UPDATE measurement_outbox SET status='expired',payload='{}'::jsonb WHERE status IN ('pending','sending') AND (created_at<now()-interval '48 hours' OR attempts>=8)");
 return {processed:rows.length,sent};}
module.exports={context,payloads,enqueue,flush};
