'use strict';
const ORIGIN='https://beanbrosbrewingco.com';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=p=>String(p.name).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const url=p=>ORIGIN+'/products/'+p.id+'/'+slug(p)+'/';
function image(p){if(p.imageKey)return ORIGIN+'/.netlify/functions/image?key='+encodeURIComponent(p.imageKey);if(p.id>=900001&&p.id<=900033)return ORIGIN+'/collections/assets/herbs/herb-'+String(p.id-900001).padStart(2,'0')+'-front.png';const names={1:'ethiopian-yirgacheffe',4:'french-roast-sumatra',5:'nicaragua',6:'mexican-chiapas',7:'bean-bros-blend',8:'brazil-legender'};return names[p.id]?ORIGIN+'/assets/products/'+names[p.id]+'.webp':null}
const active=list=>list.filter(p=>p.active&&Number.isSafeInteger(p.id)&&Number.isFinite(p.price)&&p.price>=0);
const description=p=>[p.bio,p.tastingNotes,p.roast,p.weight].filter(Boolean).join(' ').trim()||p.name+' from Bean Bros Brewing Co.';
function shell(title,desc,canonical,body,schema){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc.slice(0,160))}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc.slice(0,160))}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="${esc(schema?.image||ORIGIN+'/og-image.png')}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/assets/seo-catalog.css"><link rel="stylesheet" href="/assets/tracking.css"><script defer src="/tracking-config.js"></script><script defer src="/assets/tracking.js"></script>${schema?'<script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,'\\u003c')+'</script>':''}</head><body><a class="skip" href="#main">Skip to content</a><header><a href="/">Bean Bros Brewing Co.</a><nav><a href="/shop/">All products</a><a href="/#subscribe">Subscribe &amp; save</a></nav></header><main id="main">${body}</main><footer><a href="/shipping-returns.html">Shipping &amp; returns</a> · <a href="/privacy.html">Privacy</a> · <a href="mailto:hello@beanbrosbrewingco.com">Contact us</a></footer></body></html>`}
function productPage(p){const photo=image(p),u=url(p),desc=description(p);return shell(p.name+' | Bean Bros Brewing',desc,u,`<nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/shop/">Shop</a> / ${esc(p.name)}</nav><article class="product">${photo?`<img src="${esc(photo)}" alt="${esc(p.name)} packaging" fetchpriority="high">`:''}<div><p class="eyebrow">${esc(p.category||'Coffee')} · ${esc(p.weight)}</p><h1>${esc(p.name)}</h1><p>${esc(p.bio)}</p><p>${esc(p.tastingNotes)}</p><p>${esc([p.origin,p.roast].filter(Boolean).join(' · '))}</p><p class="price">$${p.price.toFixed(2)} USD</p><p>${p.stock>0?'In stock':'Currently sold out'}. Shipping calculated for your address at checkout.</p><a class="button" href="/?product=${p.id}#coffee">${p.stock>0?'Choose options':'View in the shop'}</a><p><a href="/shipping-returns.html">Shipping and return policy</a></p></div></article>`,{'@context':'https://schema.org','@type':'Product',name:p.name,description:desc,sku:String(p.id),...(photo?{image:photo}:{}),brand:{'@type':'Brand',name:'Bean Bros Brewing Co.'},offers:{'@type':'Offer',url:u,price:p.price.toFixed(2),priceCurrency:'USD',availability:'https://schema.org/'+(p.stock>0?'InStock':'OutOfStock'),itemCondition:'https://schema.org/NewCondition',seller:{'@type':'Organization',name:'Bean Bros Brewing Co.'}}})}
function shopPage(list){return shell('Shop Coffee, Herbs & Tea | Bean Bros Brewing','Explore the current Bean Bros coffee, herbs and tea collection. Choose your favorite roast, grind and full-size bag.',ORIGIN+'/shop/',`<h1>Find your daily favorite.</h1><p>Coffee, herbs and tea from Bean Bros Brewing.</p><div class="grid">${list.map(p=>`<article>${image(p)?`<a href="${url(p)}"><img src="${esc(image(p))}" alt="${esc(p.name)} packaging" loading="lazy"></a>`:''}<h2><a href="${url(p)}">${esc(p.name)}</a></h2><p>${esc(p.tastingNotes||p.weight)}</p><p>$${p.price.toFixed(2)} USD · ${p.stock>0?'In stock':'Sold out'}</p></article>`).join('')}</div>`)}
function feed(list){return '<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:g="http://base.google.com/ns/1.0"><channel><title>Bean Bros Brewing Co.</title><link>'+ORIGIN+'</link><description>Current Bean Bros product catalog</description>'+list.filter(p=>image(p)).map(p=>`<item><g:id>${p.id}</g:id><g:title>${esc(p.name)}</g:title><g:description>${esc(description(p))}</g:description><g:link>${esc(url(p))}</g:link><g:image_link>${esc(image(p))}</g:image_link><g:availability>${p.stock>0?'in stock':'out of stock'}</g:availability><g:price>${p.price.toFixed(2)} USD</g:price><g:condition>new</g:condition><g:brand>Bean Bros Brewing Co.</g:brand><g:product_type>${esc(p.category||'coffee')}</g:product_type></item>`).join('')+'</channel></rss>'}
function sitemap(list){return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/','/shop/','/privacy.html','/terms.html','/shipping-returns.html','/accessibility.html',...list.map(p=>url(p).slice(ORIGIN.length))].map(p=>'<url><loc>'+esc(ORIGIN+p)+'</loc></url>').join('')+'</urlset>'}
module.exports={ORIGIN,esc,slug,url,image,active,productPage,shopPage,feed,sitemap};
