// Run explicitly after changing original artwork; normal builds use checked-in derivatives.
const fs = require('node:fs');
const path = require('node:path');
const sharp = require('sharp');
const root = path.resolve(__dirname, '..');
const sources = [
 ...fs.readdirSync(path.join(root,'assets/brand')).filter(f=>f.endsWith('.jpg')).map(f=>'assets/brand/'+f),
 ...fs.readdirSync(path.join(root,'assets/products')).filter(f=>f.endsWith('.webp')&&!f.endsWith('-web.webp')).map(f=>'assets/products/'+f),
 ...fs.readdirSync(path.join(root,'collections/assets/herbs')).filter(f=>/-front\.png$/.test(f)).map(f=>'collections/assets/herbs/'+f),
 'source-images/catalog-house-blend.png',
 ...['full','merch','accessories','beanbros-travel-mug','beanbros-speckled-mug'].map(f=>'collections/assets/'+f+'.png')
];
(async()=>{
 const manifest={};let before=0,after=0;
 for(const source of sources){
  const target=source.replace(/^source-images\//,'assets/products/').replace(/\.(jpg|png|webp)$/,'-web.webp');
  const input=path.join(root,source),output=path.join(root,target);
  const {width,height,size}=await sharp(input).resize({width:1200,height:1200,fit:'inside',withoutEnlargement:true}).webp({quality:84,effort:6}).toFile(output);
  before+=fs.statSync(input).size;after+=size;
  manifest['/'+source]={src:'/'+target,width,height};
 }
 for(const [alias,source] of Object.entries(require('../netlify/functions/lib/image-aliases.json')))manifest[alias]=manifest[source];
 fs.writeFileSync(path.join(root,'netlify/functions/lib/optimized-images.json'),JSON.stringify(manifest,null,2)+'\n');
 fs.writeFileSync(path.join(root,'assets/optimized-images.js'),'// Generated by scripts/optimize-images.cjs. Unknown images and future uploads stay unchanged.\nwindow.BeanBrosImage = url => { const parsed = new URL(url, location.href); const path = parsed.pathname + (parsed.pathname === \"/.netlify/functions/image\" ? parsed.search : \"\"); return '+JSON.stringify(Object.fromEntries(Object.entries(manifest).map(([key,v])=>[key,v.src])))+'[path] || url; };\n');
 console.log(JSON.stringify({images:sources.length,originalBytes:before,optimizedBytes:after,reductionPercent:Math.round((1-after/before)*100)}));
})().catch(e=>{console.error(e);process.exitCode=1});
